name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch: ~

env:
  PATH_CHROME_ZIP: The-Content-Farm-Terminator-Chrome.zip
  PATH_FIREFOX_ZIP: The-Content-Farm-Terminator-Firefox.zip

jobs:
  build-chrome:
    name: Build project for chrome and edge
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build project
        run: yarn install --frozen-lockfile && yarn build:chrome
      - name: Save extension zip
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.PATH_CHROME_ZIP }}
          name: ${{ env.PATH_CHROME_ZIP }}
  publish-chrome:
    name: Publish extension to Chrome Web Store
    runs-on: ubuntu-latest
    needs:
      - build-chrome
    env:
      EXTENSION_ID: chhekpgdckchblnfdelceaigmlfbakgn
    steps:
      - name: Download extension zip
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PATH_CHROME_ZIP }}
          path: .
      - name: Retrieve web store token
        uses: wdzeng/chrome-extension-action@v1
        with:
          extension-id: ${{ env.EXTENSION_ID }}
          zip-path: ${{ env.PATH_CHROME_ZIP }}
          client-id: ${{ secrets.CHROME_API_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_API_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_API_REFRESH_TOKEN }}
